version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/enigma-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/enigma-backend"
    schedule:
      interval: "weekly"